# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='corpus.proto',
  package='',
  serialized_pb='\n\x0c\x63orpus.proto\"\x85\x01\n\x06Review\x12\x15\n\roverallRating\x18\x01 \x02(\x02\x12\x12\n\nfoodRating\x18\x02 \x02(\x02\x12\x16\n\x0e\x61mbianceRating\x18\x03 \x02(\x02\x12\x15\n\rserviceRating\x18\x04 \x02(\x02\x12\x13\n\x0bnoiseRating\x18\x05 \x02(\x02\x12\x0c\n\x04text\x18\x06 \x02(\t\"1\n\nRestaurant\x12\n\n\x02id\x18\x01 \x02(\r\x12\x17\n\x06review\x18\x02 \x03(\x0b\x32\x07.Review\"1\n\x0eRestaurantList\x12\x1f\n\nrestaurant\x18\x01 \x03(\x0b\x32\x0b.Restaurant')




_REVIEW = descriptor.Descriptor(
  name='Review',
  full_name='Review',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='overallRating', full_name='Review.overallRating', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='foodRating', full_name='Review.foodRating', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ambianceRating', full_name='Review.ambianceRating', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='serviceRating', full_name='Review.serviceRating', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='noiseRating', full_name='Review.noiseRating', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='text', full_name='Review.text', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=17,
  serialized_end=150,
)


_RESTAURANT = descriptor.Descriptor(
  name='Restaurant',
  full_name='Restaurant',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='Restaurant.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='review', full_name='Restaurant.review', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=152,
  serialized_end=201,
)


_RESTAURANTLIST = descriptor.Descriptor(
  name='RestaurantList',
  full_name='RestaurantList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='restaurant', full_name='RestaurantList.restaurant', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=203,
  serialized_end=252,
)


_RESTAURANT.fields_by_name['review'].message_type = _REVIEW
_RESTAURANTLIST.fields_by_name['restaurant'].message_type = _RESTAURANT

class Review(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REVIEW
  
  # @@protoc_insertion_point(class_scope:Review)

class Restaurant(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESTAURANT
  
  # @@protoc_insertion_point(class_scope:Restaurant)

class RestaurantList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESTAURANTLIST
  
  # @@protoc_insertion_point(class_scope:RestaurantList)

# @@protoc_insertion_point(module_scope)
